Truncate table Student;
GO
Truncate table Teacher;
GO
Insert into ClassUnit (TeacherID,Name) values (2,'Section 7-2')
Insert into ClassUnit (TeacherID,Name) Values (2,'Section 7-1')
Insert into ClassUnit (TeacherID,Name) values (2,'Section 8-6')
Insert into ClassUnit (TeacherID,Name) values (2,'Section 8-7')
Insert into ClassUnit (TeacherID,Name) values (2,'Section 6-4')
Insert into ClassUnit (TeacherID,Name) Values (2,'Section 6-5')



Insert into Student (ClassId, Name) Select ID,'Annabelle' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Hadley' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Peter' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Henry' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Yup' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Alexis' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Emma I' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Zak' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Cade' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Ella' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Emma P' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Kendall' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Abby' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Amelia' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Charlie' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Danny' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Elle' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Jilly' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Aspen' from ClassUnit where Name ='Section 7-1'
Insert into Student (ClassId, Name) Select ID,'Ethen' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Ethen' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Nora' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Ozzy' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Blakely' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Hollis' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Hailey' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Violet' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Avery' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Vladimir' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Isa' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Kristen' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Sydney' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Easton' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Leo' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Virginia' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Izzy' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Eden' from ClassUnit where Name ='Section 7-2'
Insert into Student (ClassId, Name) Select ID,'Karol' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Alex A' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Russell' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Patrick' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Franca' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Dharanidhar' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Amanda' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Emily D' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Ava' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Persyist' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Jamison' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Jaymee' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Preston' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Roni' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Emily L' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Allie' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Micah' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Gran' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Alex S.' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Livy' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Evan' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Gemma' from ClassUnit where Name ='Section 8-6'
Insert into Student (ClassId, Name) Select ID,'Jake ' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Patrick' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Luke' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Lucy' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Olivia' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Ellice' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Johnny' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Nishka' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Shepherd' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Alex E.' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Mikayla' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Ava' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Syd' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Josiah' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Sara' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Sofia' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Mia' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Kalea' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Gunbe' from ClassUnit where Name ='Section 8-7'
Insert into Student (ClassId, Name) Select ID,'Aria' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Jonny' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Ella' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Hana' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Mia' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Emme' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Leo' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Dez' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Elena' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Aashika' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Roebin' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Evelyn' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Lance' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Scarlett' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Isla' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Charlize' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Moksha' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Elizabeth' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Gracie' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Reno' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Franco' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Maha' from ClassUnit where Name ='Section 6-4'
Insert into Student (ClassId, Name) Select ID,'Olivia' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Charli' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Eleanor' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Logan' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Atharv' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Adriana' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Artem' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Kyla' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Claire' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Kade' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Ivy' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Megha' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Ben' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Alanna' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Savannah' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Chase' from ClassUnit where Name ='Section 6-5'
Insert into Student (ClassId, Name) Select ID,'Emma' from ClassUnit where Name ='Section 6-5'
